-- Oracle DDL for the effort tracker
CREATE TABLE teams (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    career_level VARCHAR2(100) NOT NULL,
    is_lead NUMBER(1) DEFAULT 0,
    -- is_locked added to support locking member accounts (0 = unlocked, 1 = locked)
    is_locked NUMBER(1) DEFAULT 0,
    team_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE tasks (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    details CLOB,
    hours_spent NUMBER(6,2),
    due_date DATE,
    blockers CLOB,
    comments CLOB,
    status VARCHAR2(50) DEFAULT 'in_progress',
    assignee_id NUMBER,
    creator_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_assignee FOREIGN KEY (assignee_id) REFERENCES members(id),
    CONSTRAINT fk_task_creator FOREIGN KEY (creator_id) REFERENCES members(id)
);

CREATE TABLE task_tags (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tag_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_tag_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT uq_task_member_tag UNIQUE (task_id, member_id)
);

